import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import { useRouter } from 'next/router'
import Hero from '../components/Hero'
import Footer from '../components/Footer'
import Portfolio from '../components/Portfolio'
import Banner from '../components/Banner'

const Home: NextPage = () => {
  const router = useRouter()

  return (
    
    <div >
      <Head>
        <title>Astrano</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400&family=Roboto+Mono:wght@100;200;300;400;500;600;700&family=Roboto:wght@300;400;500;700;900&family=Rubik:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
      </Head>
      <Header/>
      <Hero/>
      <Portfolio/>
      <Banner/>
      <Footer/>
    </div>
  )
}

export default Home
