import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import Hero from '../components/Hero'

const Home: NextPage = () => {
  const router = useRouter()

  return (
    
    <div className={styles.container}>
      <Head>
        <title>Astrano</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Hero/>
    </div>
  )
}

export default Home
